name: Intel Security Scan

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 4 * * sun" # 4:05 AM Sunday

jobs:
  Call-Workflow:
    uses: sfblackl-intel/testing/.github/workflows/intel_scan.yml@main